export const RECORD_TYPES = {
  // Backend-canonical record types
  PASSPORT: "PASSPORT",
  PASSPORT_CARD: "PASSPORT_CARD",
  DRIVERS_LICENSE: "DRIVERS_LICENSE",
  BIRTH_CERTIFICATE: "BIRTH_CERTIFICATE",
  SOCIAL_SECURITY_CARD: "SOCIAL_SECURITY_CARD",

  INSURANCE_POLICY: "INSURANCE_POLICY",
  MEDICAL_PROFILE: "MEDICAL_PROFILE",
  MEDICAL_PROCEDURES: "MEDICAL_PROCEDURES",
  PRESCRIPTIONS: "PRESCRIPTIONS",
  VACCINATIONS: "VACCINATIONS",
  VISION_PRESCRIPTION: "VISION_PRESCRIPTION",
  PRIVATE_HEALTH_PROFILE: "PRIVATE_HEALTH_PROFILE",

  SCHOOL_INFO: "SCHOOL_INFO",
  AUTHORIZED_PICKUP: "AUTHORIZED_PICKUP",

  PET_PROFILE: "PET_PROFILE",
  PET_SERVICE_DOCS: "PET_SERVICE_DOCS",
  PET_VET_RECORDS: "PET_VET_RECORDS",

  PREFERENCES: "PREFERENCES",
  SIZES: "SIZES",

  TRAVEL_IDS: "TRAVEL_IDS",
  LOYALTY_ACCOUNTS: "LOYALTY_ACCOUNTS",

  LEGAL_PROPERTY_DOCUMENT: "LEGAL_PROPERTY_DOCUMENT",
  OTHER_DOCUMENT: "OTHER_DOCUMENT",

  // TODO(pet-docs): consolidate legacy frontend pet doc type into backend PET_SERVICE_DOCS.
  PET_DOCUMENT: "PET_DOCUMENT",

  // Compatibility extras currently referenced in existing frontend flows.
  EDUCATION_RECORD: "EDUCATION_RECORD",
  PEOPLE_CARE_PROVIDERS: "PEOPLE_CARE_PROVIDERS",
  PET_INSURANCE: "PET_INSURANCE",
  PET_BASICS: "PET_BASICS",
  PET_CARE_PROVIDERS: "PET_CARE_PROVIDERS",
  PET_VACCINATIONS: "PET_VACCINATIONS",
  PET_FLEA_PREVENTION: "PET_FLEA_PREVENTION",
  PET_SURGERIES: "PET_SURGERIES",
} as const;

export type RecordType = typeof RECORD_TYPES[keyof typeof RECORD_TYPES];
