export const RECORD_CATEGORIES = {
  IDENTIFICATION: "IDENTIFICATION",
  MEDICAL: "MEDICAL",
  PRIVATE_HEALTH: "PRIVATE_HEALTH",
  SCHOOL_INFO: "SCHOOL_INFO",
  EDUCATION: "EDUCATION",
  PETS: "PETS",
  PREFERENCES: "PREFERENCES",
  SIZES: "SIZES",
  TRAVEL: "TRAVEL",
  LOYALTY: "LOYALTY",
  LEGAL_PROPERTY: "LEGAL_PROPERTY",
  DOCUMENTS: "DOCUMENTS",
} as const;

export type RecordCategory =
  typeof RECORD_CATEGORIES[keyof typeof RECORD_CATEGORIES];

export const CATEGORY_ORDER: RecordCategory[] = [
  RECORD_CATEGORIES.IDENTIFICATION,
  RECORD_CATEGORIES.MEDICAL,
  RECORD_CATEGORIES.PRIVATE_HEALTH,
  RECORD_CATEGORIES.SCHOOL_INFO,
  RECORD_CATEGORIES.EDUCATION,
  RECORD_CATEGORIES.PREFERENCES,
  RECORD_CATEGORIES.SIZES,
  RECORD_CATEGORIES.TRAVEL,
  RECORD_CATEGORIES.DOCUMENTS,
];

export const PERSON_CATEGORY_ORDER: RecordCategory[] = CATEGORY_ORDER.filter(
  (category) => category !== RECORD_CATEGORIES.PETS
);

export const PET_CATEGORY_ORDER: RecordCategory[] = [RECORD_CATEGORIES.PETS];
