export const RECORD_TYPES = {
  // PEOPLE
  PASSPORT: "PASSPORT",
  PASSPORT_CARD: "PASSPORT_CARD",
  DRIVERS_LICENSE: "DRIVERS_LICENSE",
  BIRTH_CERTIFICATE: "BIRTH_CERTIFICATE",
  SOCIAL_SECURITY_CARD: "SOCIAL_SECURITY_CARD",

  MEDICAL_INSURANCE: "MEDICAL_INSURANCE",
  MEDICAL_PROFILE: "MEDICAL_PROFILE",
  MEDICAL_PROCEDURES: "MEDICAL_PROCEDURES",
  PRESCRIPTIONS: "PRESCRIPTIONS",
  VACCINATIONS: "VACCINATIONS",
  VISION_PRESCRIPTION: "VISION_PRESCRIPTION",
  PRIVATE_HEALTH_PROFILE: "PRIVATE_HEALTH_PROFILE",

  SCHOOL_INFO: "SCHOOL_INFO",
  AUTHORIZED_PICKUP: "AUTHORIZED_PICKUP",
  EDUCATION_RECORD: "EDUCATION_RECORD",
  PEOPLE_CARE_PROVIDERS: "PEOPLE_CARE_PROVIDERS",

  PREFERENCES: "PREFERENCES",
  SIZES: "SIZES",
  PERSON_SIZING_PROFILE: "PERSON_SIZING_PROFILE",

  TRAVEL_IDS: "TRAVEL_IDS",
  LOYALTY_ACCOUNTS: "LOYALTY_ACCOUNTS",

  LEGAL_PROPERTY_DOCUMENT: "LEGAL_PROPERTY_DOCUMENT",
  OTHER_DOCUMENT: "OTHER_DOCUMENT",

  // PET
  PET_OVERVIEW: "PET_OVERVIEW",

  PET_BASICS: "PET_BASICS",
  PET_WEIGHT_ENTRY: "PET_WEIGHT_ENTRY",
  PET_MEDICATIONS: "PET_MEDICATIONS",
  PET_VACCINATIONS: "PET_VACCINATIONS",
  PET_SURGERIES: "PET_SURGERIES",
  PET_DIAGNOSES: "PET_DIAGNOSES",
  PET_INSURANCE: "PET_INSURANCE",

  PET_FEEDING_ROUTINE: "PET_FEEDING_ROUTINE",
  PET_BATHROOM_ROUTINE: "PET_BATHROOM_ROUTINE",
  PET_SLEEP_ROUTINE: "PET_SLEEP_ROUTINE",
  PET_FLEA_PREVENTION: "PET_FLEA_PREVENTION",
  PET_BEHAVIOR_PROFILE: "PET_BEHAVIOR_PROFILE",
  PET_CARE_PROVIDERS: "PET_CARE_PROVIDERS",
  PET_DOCUMENT: "PET_DOCUMENT",
} as const;

export type RecordType = (typeof RECORD_TYPES)[keyof typeof RECORD_TYPES];
