export const RECORD_CATEGORIES = {
  IDENTIFICATION: "IDENTIFICATION",
  MEDICAL: "MEDICAL",
  PRIVATE_HEALTH: "PRIVATE_HEALTH",
  SCHOOL: "SCHOOL",
  SCHOOL_INFO: "SCHOOL",
  PREFERENCES: "PREFERENCES",
  SIZES: "SIZES",
  TRAVEL: "TRAVEL",
  LEGAL: "LEGAL",
  LEGAL_PROPERTY: "LEGAL",
  DOCUMENTS: "DOCUMENTS",

  PET_BASICS: "PET_BASICS",
  PET_MEDICAL: "PET_MEDICAL",
  PET_CARE: "PET_CARE",
  PET_DOCUMENTS: "PET_DOCUMENTS",

  HIDDEN_LEGACY: "HIDDEN_LEGACY",
} as const;

export type RecordCategory = typeof RECORD_CATEGORIES[keyof typeof RECORD_CATEGORIES];

export const PERSON_CATEGORY_ORDER: RecordCategory[] = [
  RECORD_CATEGORIES.IDENTIFICATION,
  RECORD_CATEGORIES.MEDICAL,
  RECORD_CATEGORIES.PRIVATE_HEALTH,
  RECORD_CATEGORIES.SCHOOL,
  RECORD_CATEGORIES.PREFERENCES,
  RECORD_CATEGORIES.SIZES,
  RECORD_CATEGORIES.TRAVEL,
  RECORD_CATEGORIES.LEGAL,
  RECORD_CATEGORIES.DOCUMENTS,
];

export const PET_CATEGORY_ORDER: RecordCategory[] = [
  RECORD_CATEGORIES.PET_BASICS,
  RECORD_CATEGORIES.PET_MEDICAL,
  RECORD_CATEGORIES.PET_CARE,
  RECORD_CATEGORIES.PET_DOCUMENTS,
];
