export const KIND_OPTIONS = ["Dog", "Cat", "Bird", "Reptile", "Fish", "Small Animal", "Other"] as const;

export const DOG_BREEDS = [
  "Akita",
  "Alaskan Malamute",
  "Australian Cattle Dog",
  "Australian Shepherd",
  "Beagle",
  "Bernese Mountain Dog",
  "Bichon Frise",
  "Border Collie",
  "Boston Terrier",
  "Boxer",
  "Bulldog",
  "Cane Corso",
  "Cavalier King Charles Spaniel",
  "Chihuahua",
  "Chow Chow",
  "Cocker Spaniel",
  "Dachshund",
  "Doberman Pinscher",
  "English Setter",
  "English Springer Spaniel",
  "French Bulldog",
  "German Shepherd",
  "Golden Retriever",
  "Great Dane",
  "Greyhound",
  "Havanese",
  "Husky (Siberian Husky)",
  "Jack Russell Terrier",
  "Labrador Retriever",
  "Lhasa Apso",
  "Maltese",
  "Miniature Pinscher",
  "Miniature Schnauzer",
  "Mixed / Unknown",
  "Pekingese",
  "Pembroke Welsh Corgi",
  "Pit Bull / American Pit Bull Terrier",
  "Pomeranian",
  "Poodle (Miniature)",
  "Poodle (Standard)",
  "Poodle (Toy)",
  "Pug",
  "Rottweiler",
  "Samoyed",
  "Shiba Inu",
  "Shih Tzu",
  "Staffordshire Bull Terrier",
  "Vizsla",
  "Weimaraner",
  "West Highland White Terrier",
  "Yorkshire Terrier",
  "Other",
] as const;

export const CAT_BREEDS = [
  "Abyssinian",
  "American Curl",
  "American Shorthair",
  "Balinese",
  "Bengal",
  "Birman",
  "British Shorthair",
  "Burmese",
  "Cornish Rex",
  "Devon Rex",
  "Domestic Long Hair",
  "Domestic Medium Hair",
  "Domestic Short Hair",
  "Egyptian Mau",
  "Maine Coon",
  "Mixed / Unknown",
  "Norwegian Forest Cat",
  "Oriental Shorthair",
  "Persian",
  "Ragdoll",
  "Russian Blue",
  "Scottish Fold",
  "Siamese",
  "Siberian",
  "Sphynx",
  "Turkish Angora",
  "Other",
] as const;