/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/add-contact`; params?: Router.UnknownInputParams; } | { pathname: `/add-dependent`; params?: Router.UnknownInputParams; } | { pathname: `/add-pet`; params?: Router.UnknownInputParams; } | { pathname: `/add-profile`; params?: Router.UnknownInputParams; } | { pathname: `/add-user`; params?: Router.UnknownInputParams; } | { pathname: `/dependent-detail`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/pet-detail`; params?: Router.UnknownInputParams; } | { pathname: `/profile-saved`; params?: Router.UnknownInputParams; } | { pathname: `/user-detail`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dependents` | `/dependents`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/directory` | `/directory`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/documents` | `/documents`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/add-contact`; params?: Router.UnknownOutputParams; } | { pathname: `/add-dependent`; params?: Router.UnknownOutputParams; } | { pathname: `/add-pet`; params?: Router.UnknownOutputParams; } | { pathname: `/add-profile`; params?: Router.UnknownOutputParams; } | { pathname: `/add-user`; params?: Router.UnknownOutputParams; } | { pathname: `/dependent-detail`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/pet-detail`; params?: Router.UnknownOutputParams; } | { pathname: `/profile-saved`; params?: Router.UnknownOutputParams; } | { pathname: `/user-detail`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/dependents` | `/dependents`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/directory` | `/directory`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/documents` | `/documents`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/add-contact${`?${string}` | `#${string}` | ''}` | `/add-dependent${`?${string}` | `#${string}` | ''}` | `/add-pet${`?${string}` | `#${string}` | ''}` | `/add-profile${`?${string}` | `#${string}` | ''}` | `/add-user${`?${string}` | `#${string}` | ''}` | `/dependent-detail${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `/pet-detail${`?${string}` | `#${string}` | ''}` | `/profile-saved${`?${string}` | `#${string}` | ''}` | `/user-detail${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/dependents${`?${string}` | `#${string}` | ''}` | `/dependents${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/directory${`?${string}` | `#${string}` | ''}` | `/directory${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/documents${`?${string}` | `#${string}` | ''}` | `/documents${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/add-contact`; params?: Router.UnknownInputParams; } | { pathname: `/add-dependent`; params?: Router.UnknownInputParams; } | { pathname: `/add-pet`; params?: Router.UnknownInputParams; } | { pathname: `/add-profile`; params?: Router.UnknownInputParams; } | { pathname: `/add-user`; params?: Router.UnknownInputParams; } | { pathname: `/dependent-detail`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/pet-detail`; params?: Router.UnknownInputParams; } | { pathname: `/profile-saved`; params?: Router.UnknownInputParams; } | { pathname: `/user-detail`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dependents` | `/dependents`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/directory` | `/directory`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/documents` | `/documents`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; };
    }
  }
}
